name = "resort-booking-system"
compatibility_date = "2026-09-29"
account_id = "5fcac2dd5a04b7d73856b828efb0b8e0"
main = "worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "resort-db"
database_id = "f9b84164-300f-45a6-987d-aa1047991d6a"
